const fs=require('fs'),p=require('path'),os=require('os'),cp=require('child_process'),crypto=require('crypto');
const {chromium}=require('playwright');
const out=__dirname,repo=process.cwd(),tmp=fs.mkdtempSync(p.join(os.tmpdir(),'atlas-review-v2-')),pkg=p.join(tmp,'pkg'),store=p.join(tmp,'store'),alpha=p.join(tmp,'alpha'),beta=p.join(tmp,'beta');
fs.cpSync(p.join(repo,'dist/atlas-local-darwin-x64'),pkg,{recursive:true});
const source='export function add(a, b) { return a + b; }\nexport function checkout(a, b) { return add(a, -b); }\nexport function spin(n) { let x=0; while(x<n){x=x+1;} return x; }\n';
for(const dir of [alpha,beta]){fs.mkdirSync(dir);fs.writeFileSync(p.join(dir,'package.json'),'{"type":"module"}');fs.writeFileSync(p.join(dir,'math.js'),source);fs.writeFileSync(p.join(dir,'check.test.js'),'import {test} from "node:test"; import assert from "node:assert/strict"; test("sample",()=>assert.equal(1+1,2));\n');}
fs.writeFileSync(p.join(beta,'extra.js'),'export function betaOnly(){return 900;}\n');
let server,browser,page,session,alphaAnalysis,betaAnalysis,runId,proposal;const checks=[],errors=[];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function assert(v,m){if(!v)throw Error(m)}
async function check(name,f){try{checks.push({name,result:'PASS',detail:await f()});}catch(e){checks.push({name,result:'FAIL',detail:String(e.message||e)});}console.log(name,checks.at(-1).result);}
async function shot(name){await page.screenshot({path:p.join(out,name+'.png'),fullPage:true});}
async function nav(n){await page.locator(`.wb-nav [data-go="${n}"]`).click();}
async function select(name){await nav('explore');await page.locator('#fn-search').fill(name);await page.waitForFunction(n=>document.querySelector('#fn-list button')?.textContent.includes(n),name);await page.locator('#fn-list button').first().click();await page.waitForFunction(n=>state.selected?.name===n&&state.execProfile?.symbol===state.selected.id&&state.sourceRes?.status==='ready',name);}
async function api(path,body,method){const r=await fetch(session.url+'api/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+session.token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return {status:r.status,data};}
async function settings(argv){await nav('home');await page.locator('#settings-test-argv').fill(JSON.stringify(argv));await page.locator('#home-settings-save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('设置已生效'));}
async function openProject(dir,name){await nav('home');await page.locator('#home-open-path').fill(dir);await page.locator('#home-open-button').click();await page.waitForFunction(n=>state.projectName===n&&document.getElementById('status').textContent.includes('新项目已加载'),name,{timeout:60000});}
async function propose(diff){await nav('review');await page.locator('#patch-propose-open').click();await page.locator('#patch-input').fill(diff);const before=await page.evaluate(()=>state.patches.map(p=>p.id));await page.locator('#patch-propose').click();await page.waitForFunction(ids=>state.patches.some(p=>!ids.includes(p.id)),before);return await page.evaluate(ids=>state.patches.find(p=>!ids.includes(p.id)).id,before);}
async function verify(){await page.locator('#review-evidence-inner button').filter({hasText:'验证'}).first().click();await page.waitForFunction(()=>document.getElementById('review-evidence-inner').textContent.includes('通过（退出码 0）'),null,{timeout:90000});}
async function writeAction(label){await page.locator('#review-evidence-inner button').filter({hasText:label}).click();await page.waitForFunction(()=>document.getElementById('write-dialog').open);const message=await page.locator('#write-dialog-body').innerText();await page.locator('#write-dialog-confirm').click();return message;}
(async()=>{try{
 server=cp.spawn('./start.sh',[alpha],{cwd:pkg,detached:true,env:{...process.env,ATLAS_STORE:store},stdio:['ignore','pipe','pipe']});let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
 for(let i=0;i<300;i++){if(fs.existsSync(store)){const file=fs.readdirSync(store).find(n=>/^web-session-.*\.json$/.test(n));if(file){session=JSON.parse(fs.readFileSync(p.join(store,file)));break;}}await wait(100);}
 if(!session)throw Error('launcher did not start: '+log.replace(/token=[^\s]+/g,'token=REDACTED'));
 const contract=await api('contract'),report=await api('report');alphaAnalysis=report.data.id;
 fs.writeFileSync(p.join(out,'identity.json'),JSON.stringify({at:new Date().toISOString(),head:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),package_sha256:crypto.createHash('sha256').update(fs.readFileSync(p.join(pkg,'atlas'))).digest('hex'),binary_fingerprint:report.data.binary_fingerprint,scope:'copied final distribution launched outside repository with start.sh; own temporary sample projects'},null,2));
 browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.goto(session.url+'#token='+session.token);await page.waitForFunction(()=>state.report&&state.contract);
 await check('final package exploration and real run',async()=>{await select('checkout');await page.waitForFunction(()=>document.querySelectorAll('#graph g.node-group').length>1);await page.locator('#graph g.node-group').filter({hasText:'add'}).first().click();await page.waitForFunction(()=>state.selected?.name==='add'&&state.sourceRes?.status==='ready');await select('checkout');await nav('run');await page.locator('#exec-param-0').fill('19');await page.locator('#exec-param-1').fill('4');await page.locator('#exec-run').click();await page.waitForFunction(()=>document.querySelector('.run-hero-value')?.textContent==='15');runId=await page.evaluate(()=>state.execResultMeta.runId);await shot('01-run');return {result:15,analysis:alphaAnalysis,run:runId};});
 await check('UI background cancellation after leaving function',async()=>{await select('spin');await nav('run');await page.locator('#exec-param-0').fill('10000000000');await page.locator('#exec-run').click();await page.waitForFunction(()=>state.currentRun?.id);await select('checkout');await page.locator('#nav-tasks').click();await page.waitForFunction(()=>document.getElementById('tasks-body').textContent.includes('spin'));await page.locator('#tasks-body .task-row').filter({hasText:'spin'}).locator('button').filter({hasText:'取消'}).click();await page.waitForFunction(()=>document.getElementById('tasks-body').textContent.includes('已取消'));await shot('02-cancelled');await page.keyboard.press('Escape');return {cancelled:true};});
 await check('settings then actual isolated verification',async()=>{await settings(['node','--test']);await select('checkout');proposal=await propose('--- a/math.js\n+++ b/math.js\n@@ -2,1 +2,1 @@\n-export function checkout(a, b) { return add(a, -b); }\n+export function checkout(a, b) { return add(a, b); }\n');await verify();const evidence=await page.locator('#review-evidence-inner').innerText();assert(evidence.includes('["node","--test"]'),evidence);const cols=await page.locator('#patch-body').evaluate(e=>getComputedStyle(e).display);assert(cols==='grid','review not grid');await shot('03-review');return {proposal,test:'node --test',layout:cols};});
 await check('same input compare baseline 15 vs patch 23',async()=>{await nav('run');await page.locator('#exec-param-0').fill('19');await page.locator('#exec-param-1').fill('4');await page.locator('#run-compare-body button').filter({hasText:'以相同输入比较'}).click();await page.waitForFunction(()=>document.getElementById('run-compare-result').textContent.includes('返回'),null,{timeout:60000});const t=await page.locator('#run-compare-result').innerText();assert(t.includes('15')&&t.includes('23'),t);return t;});
 await check('apply new analysis and cross-version revert actual bytes',async()=>{await nav('review');await writeAction('检查并应用');await page.waitForFunction(()=>document.getElementById('review-evidence-inner').textContent.includes('已应用到'));assert(fs.readFileSync(p.join(alpha,'math.js'),'utf8').includes('return add(a, b);'),'apply disk differs');await page.locator('#review-evidence-inner button').filter({hasText:'打开新版本'}).click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('新版本已加载'),null,{timeout:60000});await select('checkout');assert((await page.locator('#source').innerText()).includes('return add(a, b);'),'new source missing');await nav('review');await page.waitForFunction(()=>document.getElementById('patch-body').textContent.includes('之前的分析'));await writeAction('一键撤销');await page.waitForFunction(()=>document.getElementById('review-evidence-inner').textContent.includes('已撤销'));assert(fs.readFileSync(p.join(alpha,'math.js'),'utf8')===source,'revert bytes differ');await shot('04-reverted');await openProject(alpha,'alpha');return {applied_and_reverted:true};});
 await select('checkout');await nav('run');await page.locator('#exec-param-0').fill('719');await page.locator('#exec-param-1').fill('83');await wait(800);
 await check('second project opens with independent functions',async()=>{await openProject(beta,'beta');betaAnalysis=await page.evaluate(()=>state.report.id);await select('betaOnly');assert(betaAnalysis!==alphaAnalysis,'same analysis unexpected');return {betaAnalysis};});
 await check('same-name function input draft isolation',async()=>{await select('checkout');await nav('run');const a=await page.locator('#exec-param-0').inputValue(),b=await page.locator('#exec-param-1').inputValue();await shot('05-beta-drafts');assert(a!=='719'&&b!=='83',JSON.stringify({project:'beta',alpha_draft:[719,83],actual:[a,b]}));return {a,b};});
 await check('project settings isolated on switch',async()=>{await nav('home');const current=await page.locator('#settings-test-argv').inputValue();await shot('06-beta-settings');assert(current==='[]',JSON.stringify({beta_settings:current,alpha_settings:['node','--test']}));return {current};});
 await check('opening old task preserves its analysis identity',async()=>{await page.locator('#nav-tasks').click();await page.waitForFunction(()=>document.querySelectorAll('#tasks-body .task-row').length>0);const row=page.locator('#tasks-body .task-row').filter({hasText:runId.slice(0,8)});await row.locator('button').filter({hasText:'查看结果'}).click();await page.waitForFunction(()=>document.querySelector('.run-hero'));const detail=await page.evaluate(()=>({current:state.report.id,record:state.execResult?.record.analysis_id||state.execResult?.record.spec?.analysis_id,hero:document.querySelector('.run-hero').textContent,inputs:state.execResult?.args}));await shot('07-old-task-under-beta');assert(detail.current===alphaAnalysis||!detail.hero.includes(betaAnalysis.slice(0,12)),JSON.stringify(detail));return detail;});
 await check('second project apply cannot write first project',async()=>{await select('checkout');const id=await propose('--- a/math.js\n+++ b/math.js\n@@ -2,1 +2,1 @@\n-export function checkout(a, b) { return add(a, -b); }\n+export function checkout(a, b) { return add(a, b)+1; }\n');await verify();await page.locator('#review-evidence-inner button').filter({hasText:'检查并应用'}).click();await page.waitForFunction(()=>document.getElementById('write-dialog').open);const dialog=await page.locator('#write-dialog-body').innerText();await shot('08-beta-write-confirmation');await page.locator('#write-dialog-confirm').click();await page.waitForFunction(()=>document.getElementById('review-evidence-inner').textContent.includes('已应用到'));const a=fs.readFileSync(p.join(alpha,'math.js'),'utf8'),b=fs.readFileSync(p.join(beta,'math.js'),'utf8');await shot('09-beta-applied-to-alpha');assert(a===source&&b.includes('return add(a, b)+1;'),JSON.stringify({proposal:id,viewed_project:'beta',dialog,alpha_changed:a!==source,beta_changed:b!==source}));return {target:'beta'};});
 await check('open new version stays in second project',async()=>{await page.locator('#review-evidence-inner button').filter({hasText:'打开新版本'}).click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('新版本已加载'),null,{timeout:60000});const project=await page.evaluate(()=>state.projectName);await shot('10-reindex-project');assert(project==='beta',JSON.stringify({expected:'beta',actual:project}));return {project};});
 checks.push({name:'browser JS errors',result:errors.length?'FAIL':'PASS',detail:errors});
 }catch(e){checks.push({name:'harness',result:'FAIL',detail:String(e.stack||e)});}finally{if(browser)await browser.close();if(server)try{process.kill(-server.pid,'SIGTERM');await wait(500);process.kill(-server.pid,'SIGKILL');}catch{}fs.rmSync(tmp,{recursive:true,force:true});fs.writeFileSync(p.join(out,'results.json'),JSON.stringify({scope:'independent temporary two-project real Chrome review of copied final package',checks},null,2));console.log(JSON.stringify(checks));process.exitCode=checks.some(c=>c.result==='FAIL')?1:0;}})();
