[package]
name = "atlas-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atlas-contract.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
rusqlite.workspace = true
cap-std.workspace = true
ignore.workspace = true
tempfile.workspace = true
ryu-js = "=1.0.3"

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[build-dependencies]
sha2.workspace = true
